newsapi:
  token: c6edd7ed1db24b8485922e60c38c6930
  url: http://newsapi.org/v2

spring:
  datasource:
#    driverClassName: org.h2.Driver
#    url: jdbc:h2:mem:bootexample;MODE=MySQL
    url: jdbc:mysql://localhost:32769/news_aggregator
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enable: true
      path: /h2-console